### ISSUE TITLE
BLAPI Not Posting w/Traditional Sharding

### ISSUE THREAD

**Issue by dzlandis** [botblock/BLAPI#182]
**Describe the bug**
BLAPI does not post through the `handle` function on start when using traditional sharding. It is unclear how one is meant to use BLAPI with traditional sharding. Am I meant to use `manualPost`, and if so, can an example be provided?

**To Reproduce**
1. Create a bot which uses traditional sharding (using Discord.js ShardingManager in index.ts file)
```ts
// index.ts
const manager = new ShardingManager('./dist/bot.js', { token: process.env.DISCORD_TOKEN, totalShards: 3 });
```
2. Put BLAPI in the bot.ts file (not the main index.ts file)
```ts
// bot.ts
import { Client } from 'discord.js';
import { handle, setLogging } from 'blapi';
const client = new Client();

await client.login(process.env.DISCORD_TOKEN);

const botListAPIKeys = {
  'voidbots.net': process.env.VOIDBOTS_KEY
};

setLogging({
  extended: true,
  logger: logger
});
await handle(client, botListAPIKeys);
```
3. Run code
4. Observe an error is outputted.

```
BLAPI: Error [ShardingInProcess]: Shards are still being spawned.
```

**Expected behavior**
BLAPI posts to bot lists without any issues.

**Comment by T0TProduction** [comment]
Looks to me like BLAPI tried posting before all shards were up - does it also throw this error in the second or other later runs? (If you haven't tried out, you can set the interval to 1min so you don't need to wait the default 30mins until the next post is attempted)

**Comment by T0TProduction** [comment]
@dzlandis any news?

**Comment by dzlandis** [comment]
Hi @T0TProduction, sorry for the delay. I haven't gotten the chance to test this yet but I will due so soon. 

I believe my main concern when creating this issue was that BLAPI was failing to post on startup, instead of perhaps waiting for all shards to start up before posting somehow. I don't think there would be any issues after all shards have actually started up (i'll test to confirm), but I was more worried about having to wait an additional 30 minutes-ish after it failed to post correctly on startup. My current production system (though not ideal) has my bot restart frequently and I worry it will not have the chance to post correctly in this case. I'll set the interval to one minute for testing purposes but I won't in production as I believe that will cause rate limiting issues. Hope this helps to clarify some things :)

**Comment by T0TProduction** [comment]
No worries!

It does clarify, and now I am wondering if maybe a default wait before posting for the first time of e.g. 30seconds or so would make sense, to give shards time to start up 🤔 Do you think so?

Still looking forward to your result, if later posts do work and just the first is the issue.

Regarding ratelimits, if you choose more than 3 mins for the interval, at least botblock should not complain. Not sure about all botlists though. I could Imagine 5 or 10 mins to work in production without issue. Still, IMO that's not a real solution to your issue.

**Comment by dzlandis** [comment]
Hi again @T0TProduction.

I think it would make sense to have a default wait before posting the first time. I do also think, though, that it should be configurable as larger bots tend to take longer than 30 seconds to boot up all of their shards. 

I did some more testing and was able to confirm that the issue is only with the first post. After all shards have booted up, there are no problems.

Let me know if there is any other information you need from me :)

**Comment by T0TProduction** [comment]
Thanks for the testing! 

I agree startup could be handled differently, I'll keep this issue open for tracking that.

**Comment by T0TProduction** [comment]
@dzlandis the new version was just released, please give it a try 💯
