### ISSUE TITLE
Types require "discord.js", which is not in the package.

### ISSUE THREAD

**Issue by DonovanDMC** [botblock/BLAPI#41]
**Describe the bug**

**To Reproduce**
[Package dependencies](https://github.com/botblock/BLAPI/blob/master/package.json#L56)
[require line](https://github.com/botblock/BLAPI/blob/master/src/blapi.ts#L3)

**Expected behavior**
No error is thrown.

**Screenshots**
[screenshot of error when viewing typings](https://butts-are.cool/Code_-_Insiders_oKKnFkVQcB.png)
[error when compiling](https://butts-are.cool/Code_-_Insiders_PwNgVl8hw4.png)

**Comment by DonovanDMC** [comment]
Nothing in my code needs discord.js, so it isn't installed anywhere, and since it isn't in the package.json, it isn't installed, therefore it errors.

**Comment by DonovanDMC** [comment]
I see it in the dev dependencies, yet that isn't very helpful to us out here

**Comment by MattIPv4** [comment]
Requiring the whole of discord.js just for types seems very silly. It should have some sort of parent custom type that either uses discord.js if present or some skeleton custom types?

**Comment by T0TProduction** [comment]
Agree, is that possible with typescript? 
Haven't had that situation before.

**Comment by DonovanDMC** [comment]
You can have generic types, ex:

```typescript
class Something<V> {
    someProp: V;
}```

where people could provide the client type somehow, or just copy d.js' Client type, and toss it into the code

**Comment by DonovanDMC** [comment]
You could just make a skeleton of the d.js client, as mentioned, like so:
```typescript
interface DClient {
    user?: {
        id: string;
        [k: string]: any;
    };
    shard?: {
        id: number;
        count: number;
        [k: string]: any;
    };
    guilds: Map<string, any>;
    [k: string]: any;
}
```
Though this could still throw some stuff because you can't fully do this without importing most of their types.
best bet might be just setting it to any, and telling people what to use there.

**Comment by T0TProduction** [comment]
Yeah any would be easiest, but for developing BLAPI having the correct typings would be very convenient imo.
If by the time i get to it nobody else has created a PR i'll look into typings and if its possible to "overwrite" existing d.js types with e.g. a very crude skeleton. It would then work for anyone without d.js, but if d.js exists it continues using the correct types. 
That would be the best case scenario imo.

**Comment by T0TProduction** [comment]
So, I just tried poly filling the type with an interface.
But typescript won't allow interfaces for types/classes etc. that already exist to redeclare attributes. So e.g. Client.user **has to be** the user type discord.js provides. This means we would need to copy paste all definitions they use until the smallest part for `.user`, `.shards` and `.guilds`. (which are the ones we're using)
This is an option I would like to avoid. Currently looking for other options, any ideas?

Falling back to **only** use a selfmade type that also accepts the real discord.js type is currently the better option imo. Would want to avoid that as well though, as that removes most of the convenience TS adds to development for the lib.
