### ISSUE TITLE
Add BLAPI to github packages

### ISSUE THREAD

**Issue by T0TProduction** [botblock/BLAPI#42]
We would want to add an automatic release to GitHub packages into the existing CI.
It should already exist partly but does not work fully yet. Most likely, the access key is invalid, as we probably need one from @botblock/libs directly, and not myself.

The goal:
Make it deploy to both npm and GitHub packages at the same time.

**Comment by Andre601** [comment]
I think you just need a personal access (API) token, or if you have a GitHub Action workflow, the GitHub Token...

Also, please don't mention the team again. I hate getting notifications for things I don't follow.

**Comment by MattIPv4** [comment]
You should be able to use your own personal access token if you set it up as a sercet in the repo and use it in actions.

**Comment by T0TProduction** [comment]
> I think you just need a personal access (API) token, or if you have a GitHub Action workflow, the GitHub Token...
> 
> Also, please don't mention the team again. I hate getting notifications for things I don't follow.

Ah sorry i didnt realise i was mentioning the team haha
I'll try my personal token then

**Comment by T0TProduction** [comment]
For now, this is not doable as GPR is complete garbage. Maybe I'll reopen this once they fix it.
