### ISSUE TITLE
typings: manualPost too many arguments

### ISSUE THREAD

**Issue by angeloanan** [botblock/BLAPI#54]
**Describe the bug**
The typings on `BLAPI#manualPost` is expecting 6 arguments but it really needs 3 (guildCount, botID and apiKeys) since some are optional.

**Screenshots**
![Image](https://img.angeloanan.xyz/ye7rmpR2)

**Comment by angeloanan** [comment]
The cause: https://github.com/botblock/BLAPI/blob/master/src/blapi.ts#L329

We can simply fix this by changing the `:` to an `?:`.

**Comment by T0TProduction** [comment]
Wow completely missed the optional in the typings , thanks. Would you like to open a PR?

**Comment by angeloanan** [comment]
Sure

**Comment by angeloanan** [comment]
Ready to pull

**Comment by T0TProduction** [comment]
released it with v 1.3.3 👍
