### ISSUE TITLE
Add VoidBots.net to BLAPI

### ISSUE THREAD

**Issue by HyenaLtd** [botblock/BLAPI#60]
**Is your feature request related to a problem? Please describe.**
VoidBots.net isn't listed on BLAPI and therefore should be added.

**Describe the solution you'd like**
Adding voidbots.net to BLAPI should be considered.

**Additional context**
You can find a link to their documentation [here](https://docs.voidbots.net/bot-apis/server-count-api).

**Comment by MattIPv4** [comment]
As VoidBots is listed on BotBlock with API data present, blapi will already have support for it even though it isn't listed here -- assuming you haven't disabled the BotBlock feature in the library.

**Comment by HyenaLtd** [comment]
Then adding it's web domain in the list of supported domains would be appreciated.
