### ISSUE TITLE
Why don't the bot's users appear on discordbotlist.com?

### ISSUE THREAD

**Issue by taksumaki** [botblock/BLAPI#62]
**Describe the bug**
I see that if you update what is the number of servers that the bot has, but you don't see that it updates the number of users that the bot has, on the page it shows as "Unknown" and I do it manually if I can put it, but this package does not put that field for that page, and I imagine that also for other pages that I have not tried.

**To Reproduce**
1. Set the handle.
2. Wait for the bot statistics to update on the bot list pages.
3. See how in discordbotlist.com the number of users that the bot has is not updated (I have not tried with the other pages).

**Expected behavior**
See the total number of servers with the bot and the total number of users with the bot on discordbotlist.com (or on other pages that I have not tried).

**Screenshots**
![image](https://user-images.githubusercontent.com/56084970/97653363-3b3f0f80-1a26-11eb-895b-9f50d5be488b.png)

**Comment by advaith1** [comment]
not a bug; the BotBlock API doesn't support a users field since only one bot list has it. there's a botblock feature request for it at https://github.com/botblock/BotBlock.org/issues/79
