### ISSUE TITLE
Any example of how to do it with Sharding Manager?

### ISSUE THREAD

**Issue by taksumaki** [botblock/BLAPI#63]
In the documentation I do not see an example of how to do it with the Sharding Manager of Discord.js, I would like to know how to do it since I cannot put the handler method in the onReady of my Discord client because of the Shards that are being created, no they all have the same guild value.

**Comment by advaith1** [comment]
does it error if you use it in your normal ready event? it should automatically fetch the count from each shard

**Comment by T0TProduction** [comment]
closed due to inactivity - lmk if this comes up again
