### ISSUE TITLE
BLAPI NPM Package Not Working On Docker-Compose?

### ISSUE THREAD

**Issue by MaximKing1** [botblock/BLAPI#67]
**Describe the bug**
I was running the bot on a standard PM2 server config all fine now we have switched to Docker-Compose and the BLAPI will show no errors at all and at the start shows its working just no bot lists have been updated? 

**To Reproduce**
Make a bot using Docker-Compose and send the stats to a botlist using the AutoPost with it set to 60 minutes.

**Expected behavior**
should post.

**Comment by jacobmitchell04** [comment]
I'm not entirely sure how Docker is going to cause this issue, it seems more like an issue with the bot. Is there a particular error you're receiving? If so, what is it? Nobody can really help you unless you give more information. Saying 'should post' is not sufficient enough,

**Comment by jacobmitchell04** [comment]
User confirmed it wasn't a Docker issue - closing.
