### ISSUE TITLE
Using Sharding Does Not Post Any Stats..

### ISSUE THREAD

**Issue by MaximKing1** [botblock/BLAPI#68]
**Describe the bug**
No stats have bene posted to any bot list when i started using sharding...

**To Reproduce**
1. Get a sharded bot 
2. Use the blapi post though your API with 60 minute
3. wait 1 hour and see nothink posted

**Expected behavior**
Should post all stats and shards, i tried without sharding and worked again.

**Question**
is there anything i have to do to use Sharding with it?

**Comment by MaximKing1** [comment]
Note:
The BLAPI is in the index not in the Sharding file..

**Comment by jacobmitchell04** [comment]
What version of Discord.js are you using?

**Comment by MaximKing1** [comment]
latest version i litrally updated like half an hour ago xD

**Comment by MaximKing1** [comment]
```
const apiKeys = {
    "bladebotlist.xyz": process.env.BLADEBOTLIST,
    "discord.bots.gg": process.env.DBOTSGG,
};
blapi.handle(client, apiKeys, 60)  
```
this is the code in the index file

**Comment by T0TProduction** [comment]
Does it log anything? 
Any errors, or even just the first "bot is not ready yet, will start posting next time" ?
You could try turning extended logging on (like described in the readme) to see if anything pops up there

**Comment by MaximKing1** [comment]
i will do but it should work with shading right and should i add to the Sharding file and insted of client use manager?

**Comment by MaximKing1** [comment]
im testing now with the extra logging and will post errror in here if i get one if not i dont know what to do..

**Comment by MaximKing1** [comment]
i have an error

```
Strider-Testing | (node:1) UnhandledPromiseRejectionWarning: Error: Handler doesn't return strings
Strider-Testing |     at ShardingClient.registerCustomFieldHandler (/usr/src/Sharding-Test/node_modules/statcord.js/src/ShardingClient.js:337:70)
Strider-Testing |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
Strider-Testing | (Use `node --trace-warnings ...` to show where the warning was created)

Strider-Testing | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

Strider-Testing | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by T0TProduction** [comment]
> i have an error
> 
> ```
> Strider-Testing | (node:1) UnhandledPromiseRejectionWarning: Error: Handler doesn't return strings
> Strider-Testing |     at ShardingClient.registerCustomFieldHandler (/usr/src/Sharding-Test/node_modules/statcord.js/src/ShardingClient.js:337:70)
> Strider-Testing |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> Strider-Testing | (Use `node --trace-warnings ...` to show where the warning was created)
> 
> Strider-Testing | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> 
> Strider-Testing | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```

that error doesn't come from blapi, but from statcord though

**Comment by MaximKing1** [comment]
Sorry about that Idk what I even was doing tbh. I need to go though all the logs and find the errror as at the moment left for 3 hours and nothink so far... I’ve check all 6 lists

**Comment by T0TProduction** [comment]
if you have extended logging on, blapi will post at least once per attempt to post your stats. so if that doesn't happen, there's some big issue involved, most likely not even on blapis side.

for "debugging", you could also set the timer to less than 60mins btw

**Comment by MaximKing1** [comment]
Yeah what’s the minimum before it won’t go though your api? I’ll try 20 mins if I can do 10 minutes perfect for testing...

**Comment by MaximKing1** [comment]
Also a question can I attach this to my Sharding Manager? Instead of using my client use my Manager maybe then it will work?

**Comment by MaximKing1** [comment]
I’ve tried adding to the Manager and I get the first Discord Client not ready etc after that I waited and didn’t post I couldn’t find a error in console buts it’s late and probably missed it somehow..

**Comment by T0TProduction** [comment]
> Yeah what’s the minimum before it won’t go though your api? I’ll try 20 mins if I can do 10 minutes perfect for testing...

You can do any amount of Minuten, but 3 or below will Not use tue botlist API but instead call all botlists independently (should still Work though, so you could use 1min interval)

Iirc for sharding we want blapi to be called Not in the Manager, but all shards. This is because we can then suplly Info about Alls shards to the botlists. The Main Poster will Always be shard 0, so If you can distinguish them, the errors (of there are any) should be coming from there

**Comment by MaximKing1** [comment]
So I have set it to 3 minutes so I can test it out and see if it posts I can say it is in the main index.js file using a required thingy like this maybe could be the issue...

```js
const botlists = require(“PATH”);
botlists(client)
```

**Comment by MaximKing1** [comment]
Hello? still not working idk what to do now no errors either and when using non sharding it works...

**Comment by T0TProduction** [comment]
idrk what to answer, you didnt give me any more info, that code means nothing to me

did you activate extended logging?
did it log *anything*?

**Comment by MaximKing1** [comment]
i did and nothink extra was logged just the client not ready waiting to post at the start...

**Comment by T0TProduction** [comment]
seems to me like you are not using the lib correctly, because it should always log *something*
can you share the snippets that initialize it (and how you initialize the discord.js client, etc.?
otherwise, I fear I cant really help

**Comment by MaximKing1** [comment]
Okay lll get it one second...

**Comment by T0TProduction** [comment]
gonna close this because there's no follow-up. if it comes up again, well reopen.
