### ISSUE TITLE
BLAPI Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by kaname-png** [botblock/BLAPI#75]
**Describe the bug**
I can't send my bot stats because I get an error.

**To Reproduce**
1. Post new stats

**Expected behavior**
That the statistics are posted correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/56084970/115641125-b26aa780-a2d5-11eb-82d5-ddebb5d04cde.png)

**Additional context**
```
[ERROR] BLAPI Error: connect ETIMEDOUT 172.67.175.211:443
```

**Comment by T0TProduction** [comment]
What lists are you posting to? 
Did you turn off the use of botblock?
Could be that just a specific one ist down, which doesn't have to do with any issues on our side.

But after seeing this we should definitely add which endpoint is failing to the errors, to make finding the source of the error easier.

**Comment by kaname-png** [comment]
```ts
const apiKeys = {
      'discord.bots.gg': 'token',
      'discordbotlist.com': 'token',
      'discord.boats': 'token',
      'bots.ondiscord.xyz': 'token',
      'voidbots.net': 'token',
      'bots.discordlabs.org': 'token',
      'top.gg': 'token',
    };

await manualPost(guildsCountShards, this.client.user.id, apiKeys, this.client.shardId, this.client.shard.count);
```

**Comment by T0TProduction** [comment]
Could you turn on extended logging and see what it logs before the error is thrown?

**Comment by kaname-png** [comment]
The problem seems to have stopped, I have not received that error message again.
