### ISSUE TITLE
Cannot read property 'size' of undefined in blapi.js

### ISSUE THREAD

**Issue by ddugovic** [botblock/BLAPI#78]
**Describe the bug**
This is probably somehow a bug in https://github.com/ddugovic/lishogi-discord , but I don't understand how to troubleshoot it.  Upon attempting to retrieve the server count, my bot crashes.

**To Reproduce**
1. Clone https://github.com/ddugovic/lishogi-discord & install dependencies
2. Supply config.json with a valid Discord token
3. /usr/bin/node /home/lichess/lichess-discord/index.js

**Expected behavior**
Bot does not crash

**Screenshots**
```
lichess@vps178028:~/lichess-discord$ /usr/bin/node /home/lichess/lichess-discord/index.js
[ERROR] BLAPI Discord client seems to not be connected yet, so we're skipping this run of the post. We will try again in 1 minutes.
Bot is online!
2 users, in 1 servers connected.
Uncaught Promise Error:  TypeError: Cannot read property 'size' of undefined
    at /home/lichess/lichess-discord/node_modules/blapi/dist/blapi.js:241:42
    at step (/home/lichess/lichess-discord/node_modules/blapi/dist/blapi.js:57:23)
    at Object.next (/home/lichess/lichess-discord/node_modules/blapi/dist/blapi.js:38:53)
    at /home/lichess/lichess-discord/node_modules/blapi/dist/blapi.js:32:71
    at new Promise (<anonymous>)
    at __awaiter (/home/lichess/lichess-discord/node_modules/blapi/dist/blapi.js:28:12)
    at handleInternal (/home/lichess/lichess-discord/node_modules/blapi/dist/blapi.js:203:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**Additional context**
Bot is hosted on OVH.  I just switched to using this library from using dblapi.js which produced a similar error.

**Comment by T0TProduction** [comment]
just had a look at your code
1. please don't require during runtime, do that already in the beginning of the file (unrelated to this issue though)
2. as documented in the readme, we support discord.js v12. According to your package.json you use v11. You could still use this lib with the "manual posting", but in general I would recommend you update discord.js for your bot anyways. Then the issue should also be fixed

If updating discord.js does not fix the issue, we can reopen this
