### ISSUE TITLE
Add support for discord-botlist.eu

### ISSUE THREAD

**Issue by L0SER8228** [botblock/BLAPI#79]
It's a great work. I appreciate 😀❤️. It would be better if you add support for more sites. I've found one `discord-botlist.eu`.

**Comment by T0TProduction** [comment]
the botlist is listed in botblock, but apparently it doesn't have an API: https://botblock.org/lists/discord-botlist.eu

if it does have an API, please add a request on the botblock discord server, as BLAPI simply uses it as source of truth, this package doesn't actually add botlist information to botblock

**Comment by L0SER8228** [comment]
No, it doesn't have any endpoints yet . You have to manually write and post the stats
