### ISSUE TITLE
Ban Support 🤔

### ISSUE THREAD

**Issue by TheRealToxicDev** [botblock/BLAPI#81]
Hey everyone I didn’t know how else to go about doing this so I figured maybe I should just make a issue. About a month or two ago (maybe longer) I was banned from the BotBlock server for “being toxic” after simply asking for support and having a member attack me but anyways that’s not what I’m here for

I was wondering if it’s possible for me to appeal this ban, I am deeply sorry for my actions that day I was just having a bad day in general and I realize now that maybe I should have just said nothing to the person who started the argument.

90% of our users for both Paradise and Infinity use the BotBlock API and honestly the best way I can see to offer them any support they may need with these lists is to be a member of the server.

My actions on the day of my ban were uncalled for and that I understand if given another chance I promise I will keep to myself unless directly asked for assistance ❤️

Edit: I just realized I posted this on the API Repo not the main Repo my bad 😬 sorry I just woke up like 20 mins ago lol 

Thanks in Advance
- Toxic Dev

**Comment by T0TProduction** [comment]
I'm forwarding this to the appropriate people, but I don't have any say in this (just the dev of this lib)

**Comment by TheRealToxicDev** [comment]
Yeah I realized after that I opened this issue on the wrong lib if any but wasn’t sure how else to go about trying to appeal a ban so no worries I understand thanks for doing what you can ❤️ @T0TProduction

**Comment by Connor200024** [comment]
All the best! ❤

**Comment by T0TProduction** [comment]
Congrats you've been unbanned. but next time please don't open an issue, e.g. just DM someone (even me)
Discord usernames are in the repo descriptions.

**Comment by TheRealToxicDev** [comment]
> Congrats you've been unbanned. but next time please don't open an issue, e.g. just DM someone (even me)
> Discord usernames are in the repo descriptions.

Sorry about creating the issue and thanks again xD
